### ISSUE TITLE
How did you figure it out?

### ISSUE THREAD

**Issue by stever123** [manwhoami/OSXChromeDecrypt#1]
Hello there,

First of all, well done sir - It really works just great!
But how did you figure out what way to approach this, like decrypting the passwords the correct way etc.?
I know that it seems weird that I post this question as an issue but I do not really know where I should ask you a question so.. ;-)

Thanks! Much appreciated!

**Comment by manwhoami** [comment]
Hey,

Thanks for your kind words. Through a lot of research, trial and error, and messing around with Chrome and macOS I was able to achieve the final product here. I use this process for most of the code in my repositories. I set a goal for decrypting chrome passwords, and did the necessary research and work to reach that goal, crypto research, chrome research, apple keychain research, python standard libraries for no dependencies and optimal speed, etc. 

Set a goal and do not give up until you reach it (sounds cliche, but I have found it to be an immensely helpful, and valid, mantra). I had had the idea for this project for a few months before I got around to implementing it, and when that time came it took me a while to put all the moving pieces together. When you get discouraged, which you will, just keep working through it. Do more research, go deeper with your understanding of the code and related computer science concepts. You will reach your goal at some point, although it may not be clear when. What is certain is that if you give up, you never will!
