### ISSUE TITLE
Piping to text

### ISSUE THREAD

**Issue by barrett092** [manwhoami/OSXChromeDecrypt#10]
Getting an error when one tries to pipe into text:

python /Volumes/BashBunny/payloads/switch2/chrome_passwords.py > /Volumes/BashBunny/loot/PassCrush/chromepwd.txt
Traceback (most recent call last):
  File "/Volumes/BashBunny/payloads/switch2/chrome_passwords.py", line 231, in <module>
    chrome(chrome_data, safe_storage_key)
  File "/Volumes/BashBunny/payloads/switch2/chrome_passwords.py", line 204, in chrome
    utfout(entry["url"]), end))
  File "/Volumes/BashBunny/payloads/switch2/chrome_passwords.py", line 134, in utfout
    return inputvar.encode(sys.stdout.encoding, errors='replace')
TypeError: encode() argument 1 must be string, not None

Think it has something to do with the UTF-8 encoding because if you run:

export PYTHONIOENCODING='utf-8

Before the script, it works fine.

**Comment by manwhoami** [comment]
Resolved in the latest commit [881ee27](https://github.com/manwhoami/OSXChromeDecrypt/commit/881ee27847e456cf9e0a28861578a3f8e3124be6). Thanks for reporting.

**Comment by barrett092** [comment]
Thanks!

**Comment by barrett092** [comment]
Great tool
