### ISSUE TITLE
error

### ISSUE THREAD

**Issue by NassimMhb** [manwhoami/OSXChromeDecrypt#3]
hello i have an error in line 60 about line 37 key=...

Traceback (most recent call last):
  File "chrome_passwords.py", line 60, in <module>
    for i, x in enumerate(chrome_process(safe_storage_key, "%s" % profile)):
  File "chrome_passwords.py", line 37, in chrome_process
    key = hashlib.pbkdf2_hmac('sha1', safe_storage_key, b'saltysalt', 1003)[:16]
AttributeError: 'module' object has no attribute 'pbkdf2_hmac'

can you help me for that thanks.

**Comment by manwhoami** [comment]
Strange! What version of macOS / OS X are you running on? Also, what version of python?

**Comment by NassimMhb** [comment]
The version of python is 2.7 and the OS X 's version is 10.9.5

**Comment by Banaanhangwagen** [comment]
Same problem here. 
Python 2.7.6 and OS X 10.10.1

**Comment by NassimMhb** [comment]
ok thank you

**Comment by manwhoami** [comment]
The pbkdf2_hmac module was added to python in 2.7.8 it would seem. 

I have started working on implementing a backport of this module into this program. I will comment here when it is completed!

Thanks for reporting!

**Comment by manwhoami** [comment]
Resolved, see the latest commit. This program will now work on any version of Python 2.x.
