### ISSUE TITLE
Passwords always reply with "R"

### ISSUE THREAD

**Issue by iownbish** [manwhoami/OSXChromeDecrypt#4]
tried this on the standalone version and the one in Bella, same error

**Comment by manwhoami** [comment]
Do you mean they return the password "R"? Could you post a screenshot of the issue please?

**Comment by iownbish** [comment]
[uh]-[[94m~[0m] chrome_dump
[92mPasswords for Chrome Profile[0m -> [[95mProfile 1[0m]
   [32m[1][0m [1mhttps://www.freelancer.com/[0m
	[32mUser[0m: krs@aol.com
	[32mPass[0m: R
   [32m[2][0m [1mhttps://webmail.1and1.com/[0m
	[32mUser[0m: ezekiel@Transportationconsultingservicesllc.com
	[32mPass[0m: R
   [32m[3][0m [1mhttps://accounts.google.com/ServiceLogin[0m
	[32mUser[0m: transportationconsultingtcs
	[32mPass[0m: R
   [32m[4][0m [1mhttps://www.facebook.com/[0m
	[32mUser[0m: krs@aol.com
	[32mPass[0m: R
   [32m[5][0m [1mhttps://www.import.io/signup/[0m
	[32mUser[0m: krs@aol.com
	[32mPass[0m: R
   [32m[6][0m [1mhttps://www.guru.com/login.aspx[0m
	[32mUser[0m: krs@aol.com
	[32mPass[0m: R

**Comment by manwhoami** [comment]
Please post a log with no identifying information.

**Comment by iownbish** [comment]
[uh]-[[94m~[0m] chrome_safe_storage
[93m[*] [0mFound the following keychains for [uh]:
	[/Users/uh/Library/Keychains/login.keychain-db]
[93m[*] [0mUsing [/Users/uh/Library/Keychains/login.keychain-db] as keychain.
[94m[*] [0mChrome Key: [QPCsuuNC8E94DuhU10KtUw==]
[uh]-[[94m~[0m] chrome_dump
[92mPasswords for Chrome Profile[0m -> [[95mProfile 1[0m]
   [32m[1][0m [1mhttps://www.freelancer.com/[0m
	[32mUser[0m: krs@aol.com
	[32mPass[0m: R
   [32m[2][0m [1mhttps://webmail.1and1.com/[0m
	[32mUser[0m: ezekiel@Transportationconsultingservicesllc.com
	[32mPass[0m: R
   [32m[3][0m [1mhttps://accounts.google.com/ServiceLogin[0m
	[32mUser[0m: transportationconsultingtcs
	[32mPass[0m: R
   [32m[4][0m [1mhttps://www.facebook.com/[0m
	[32mUser[0m: krs@aol.com
	[32mPass[0m: R
   [32m[5][0m [1mhttps://www.import.io/signup/[0m
	[32mUser[0m: krs@aol.com
	[32mPass[0m: R
   [32m[6][0m [1mhttps://www.guru.com/login.aspx[0m
	[32mUser[0m: krs@aol.com
	[32mPass[0m: R
   [32m[7][0m [1mhttps://support.t-mobile.com/create-account.jspa[0m
	[32mUser[0m: keefrox
	[32mPass[0m: R
   [32m[8][0m [1mhttps://account.t-mobile.com/oauth2/v1/auth[0m
	[32mUser[0m: 2082759931
	[32mPass[0m: R
   [32m[9][0m [1mhttps://squareup.com/signup[0m
	[32mUser[0m: snitchaclaus@gmail.com
	[32mPass[0m: R
   [32m[10][0m [1mhttps://securea.mlb.com/enterworkflow.do[0m
	[32mUser[0m: krs@aol.com
	[32mPass[0m: R
   [32m[11][0m [1mhttps://www.directv.com/Channels/HBO-HD-East-501[0m
	[32mUser[0m: krs@aol.com
	[32mPass[0m: R
   [32m[12][0m [1mhttps://github.com/login[0m
	[32mUser[0m: iownbish
	[32mPass[0m: R
   [32m[13][0m [1mhttps://airtable.com/signup[0m
	[32mUser[0m: krs@aol.com
	[32mPass[0m: R

**Comment by iownbish** [comment]
oh sorry, my bad

**Comment by iownbish** [comment]
[uh]-[[94m~[0m] chrome_safe_storage
[93m[*] [0mFound the following keychains for [uh]:
	[/Users/uh/Library/Keychains/login.keychain-db]
[93m[*] [0mUsing [/Users/uh/Library/Keychains/login.keychain-db] as keychain.
[94m[*] [0mChrome Key: [QPCsuuNC8E94DuhU10KtUw==]
[uh]-[[94m~[0m] chrome_dump
[92mPasswords for Chrome Profile[0m -> [[95mProfile 1[0m]
   [32m[1][0m [1mhttps://www.freelancer.com/[0m
	[32mUser[0m:  ******
	[32mPass[0m: R
   [32m[2][0m [1mhttps://webmail.1and1.com/[0m
	[32mUser[0m:  ******
	[32mPass[0m: R
   [32m[3][0m [1mhttps://accounts.google.com/ServiceLogin[0m
	[32mUser[0m:  ******
	[32mPass[0m: R
   [32m[4][0m [1mhttps://www.facebook.com/[0m
	[32mUser[0m:  ******
	[32mPass[0m: R
   [32m[5][0m [1mhttps://www.import.io/signup/[0m
	[32mUser[0m:  ******
	[32mPass[0m: R
   [32m[6][0m [1mhttps://www.guru.com/login.aspx[0m
	[32mUser[0m:  ******
	[32mPass[0m: R
   [32m[7][0m [1mhttps://support.t-mobile.com/create-account.jspa[0m
	[32mUser[0m:  ******
	[32mPass[0m: R
   [32m[8][0m [1mhttps://account.t-mobile.com/oauth2/v1/auth[0m
	[32mUser[0m:  ******
	[32mPass[0m: R
   [32m[9][0m [1mhttps://squareup.com/signup[0m
	[32mUser[0m:  ******
	[32mPass[0m: R
   [32m[10][0m [1mhttps://securea.mlb.com/enterworkflow.do[0m
	[32mUser[0m:  ******
	[32mPass[0m: R
   [32m[11][0m [1mhttps://www.directv.com/Channels/HBO-HD-East-501[0m
	[32mUser[0m:  ******
	[32mPass[0m: R
   [32m[12][0m [1mhttps://github.com/login[0m
	[32mUser[0m:  ******
	[32mPass[0m: R
   [32m[13][0m [1mhttps://airtable.com/signup[0m
	[32mUser[0m: ******
	[32mPass[0m: R

**Comment by manwhoami** [comment]
Quite strange! I will look into this issue and report back here. Thanks for reporting!

**Comment by manwhoami** [comment]
Closing due to lack of response.
